// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace WebApplication1 {
	
	
	public partial class _Default {
		
		protected System.Web.UI.HtmlControls.HtmlForm form1;
		
		protected System.Web.UI.WebControls.TextBox txtInput;
		
		protected System.Web.UI.WebControls.Button Button1;
		
		protected System.Web.UI.WebControls.Button Button3;
		
		protected System.Web.UI.WebControls.Button Button2;
		
		protected System.Web.UI.WebControls.Button Button4;
		
		protected System.Web.UI.WebControls.Button Button5;
		
		protected System.Web.UI.WebControls.Button Button6;
		
		protected System.Web.UI.WebControls.Literal litBengali;
		
		protected System.Web.UI.WebControls.Literal litOutput;
		
		protected System.Web.UI.WebControls.TreeView treeAnalysis;
	}
}
