// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace NunitTest.NBNLPService {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="BNLPServiceSoap", Namespace="http://tempuri.org/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BNLPService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TranslateOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslateAnalysisOperationCompleted;
        
        private System.Threading.SendOrPostCallback TranslateSiteOperationCompleted;
        
        public BNLPService() {
            this.Url = "http://127.0.0.1:8080/BNLPService.asmx";
        }
        
        public BNLPService(string url) {
            this.Url = url;
        }
        
        public event TranslateCompletedEventHandler TranslateCompleted;
        
        public event TranslateAnalysisCompletedEventHandler TranslateAnalysisCompleted;
        
        public event TranslateSiteCompletedEventHandler TranslateSiteCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Translate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string Translate(string Text) {
            object[] results = this.Invoke("Translate", new object[] {
                        Text});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginTranslate(string Text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Translate", new object[] {
                        Text}, callback, asyncState);
        }
        
        public string EndTranslate(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void TranslateAsync(string Text) {
            this.TranslateAsync(Text, null);
        }
        
        public void TranslateAsync(string Text, object userState) {
            if ((this.TranslateOperationCompleted == null)) {
                this.TranslateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslateCompleted);
            }
            this.InvokeAsync("Translate", new object[] {
                        Text}, this.TranslateOperationCompleted, userState);
        }
        
        private void OnTranslateCompleted(object arg) {
            if ((this.TranslateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslateCompleted(this, new TranslateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TranslateAnalysis", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string TranslateAnalysis(string Text) {
            object[] results = this.Invoke("TranslateAnalysis", new object[] {
                        Text});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginTranslateAnalysis(string Text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TranslateAnalysis", new object[] {
                        Text}, callback, asyncState);
        }
        
        public string EndTranslateAnalysis(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void TranslateAnalysisAsync(string Text) {
            this.TranslateAnalysisAsync(Text, null);
        }
        
        public void TranslateAnalysisAsync(string Text, object userState) {
            if ((this.TranslateAnalysisOperationCompleted == null)) {
                this.TranslateAnalysisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslateAnalysisCompleted);
            }
            this.InvokeAsync("TranslateAnalysis", new object[] {
                        Text}, this.TranslateAnalysisOperationCompleted, userState);
        }
        
        private void OnTranslateAnalysisCompleted(object arg) {
            if ((this.TranslateAnalysisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslateAnalysisCompleted(this, new TranslateAnalysisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TranslateSite", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public string TranslateSite(string Text) {
            object[] results = this.Invoke("TranslateSite", new object[] {
                        Text});
            return ((string)(results[0]));
        }
        
        public System.IAsyncResult BeginTranslateSite(string Text, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("TranslateSite", new object[] {
                        Text}, callback, asyncState);
        }
        
        public string EndTranslateSite(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        public void TranslateSiteAsync(string Text) {
            this.TranslateSiteAsync(Text, null);
        }
        
        public void TranslateSiteAsync(string Text, object userState) {
            if ((this.TranslateSiteOperationCompleted == null)) {
                this.TranslateSiteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTranslateSiteCompleted);
            }
            this.InvokeAsync("TranslateSite", new object[] {
                        Text}, this.TranslateSiteOperationCompleted, userState);
        }
        
        private void OnTranslateSiteCompleted(object arg) {
            if ((this.TranslateSiteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TranslateSiteCompleted(this, new TranslateSiteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    public partial class TranslateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void TranslateCompletedEventHandler(object sender, TranslateCompletedEventArgs args);
    
    public partial class TranslateAnalysisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslateAnalysisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void TranslateAnalysisCompletedEventHandler(object sender, TranslateAnalysisCompletedEventArgs args);
    
    public partial class TranslateSiteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TranslateSiteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    public delegate void TranslateSiteCompletedEventHandler(object sender, TranslateSiteCompletedEventArgs args);
}
