//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DBNLPModel", "FK_Items_OutcomePattern", "OutcomePattern", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbWriter.OutcomePattern), "Items", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbWriter.Item), true)]
[assembly: EdmRelationshipAttribute("DBNLPModel", "FK_OutcomeLabel_Module", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbWriter.Module), "OutcomeLabel", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbWriter.OutcomeLabel), true)]
[assembly: EdmRelationshipAttribute("DBNLPModel", "FK_OutcomePattern_Module", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbWriter.Module), "OutcomePattern", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbWriter.OutcomePattern), true)]
[assembly: EdmRelationshipAttribute("DBNLPModel", "FK_Predicate_Module", "Module", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DbWriter.Module), "Predicate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbWriter.Predicate), true)]
[assembly: EdmRelationshipAttribute("DBNLPModel", "FK_Parameter_Predicate", "Predicate", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DbWriter.Predicate), "Parameter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbWriter.Parameter), true)]

#endregion

namespace DbWriter
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBNLPEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBNLPEntities object using the connection string found in the 'DBNLPEntities' section of the application configuration file.
        /// </summary>
        public DBNLPEntities() : base("name=DBNLPEntities", "DBNLPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBNLPEntities object.
        /// </summary>
        public DBNLPEntities(string connectionString) : base(connectionString, "DBNLPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBNLPEntities object.
        /// </summary>
        public DBNLPEntities(EntityConnection connection) : base(connection, "DBNLPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Item> Items
        {
            get
            {
                if ((_Items == null))
                {
                    _Items = base.CreateObjectSet<Item>("Items");
                }
                return _Items;
            }
        }
        private ObjectSet<Item> _Items;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Module> Modules
        {
            get
            {
                if ((_Modules == null))
                {
                    _Modules = base.CreateObjectSet<Module>("Modules");
                }
                return _Modules;
            }
        }
        private ObjectSet<Module> _Modules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OutcomeLabel> OutcomeLabels
        {
            get
            {
                if ((_OutcomeLabels == null))
                {
                    _OutcomeLabels = base.CreateObjectSet<OutcomeLabel>("OutcomeLabels");
                }
                return _OutcomeLabels;
            }
        }
        private ObjectSet<OutcomeLabel> _OutcomeLabels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<OutcomePattern> OutcomePatterns
        {
            get
            {
                if ((_OutcomePatterns == null))
                {
                    _OutcomePatterns = base.CreateObjectSet<OutcomePattern>("OutcomePatterns");
                }
                return _OutcomePatterns;
            }
        }
        private ObjectSet<OutcomePattern> _OutcomePatterns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Parameter> Parameters
        {
            get
            {
                if ((_Parameters == null))
                {
                    _Parameters = base.CreateObjectSet<Parameter>("Parameters");
                }
                return _Parameters;
            }
        }
        private ObjectSet<Parameter> _Parameters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Predicate> Predicates
        {
            get
            {
                if ((_Predicates == null))
                {
                    _Predicates = base.CreateObjectSet<Predicate>("Predicates");
                }
                return _Predicates;
            }
        }
        private ObjectSet<Predicate> _Predicates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Temp> Temps
        {
            get
            {
                if ((_Temps == null))
                {
                    _Temps = base.CreateObjectSet<Temp>("Temps");
                }
                return _Temps;
            }
        }
        private ObjectSet<Temp> _Temps;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Items EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToItems(Item item)
        {
            base.AddObject("Items", item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModules(Module module)
        {
            base.AddObject("Modules", module);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OutcomeLabels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOutcomeLabels(OutcomeLabel outcomeLabel)
        {
            base.AddObject("OutcomeLabels", outcomeLabel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the OutcomePatterns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOutcomePatterns(OutcomePattern outcomePattern)
        {
            base.AddObject("OutcomePatterns", outcomePattern);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Parameters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToParameters(Parameter parameter)
        {
            base.AddObject("Parameters", parameter);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Predicates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredicates(Predicate predicate)
        {
            base.AddObject("Predicates", predicate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Temps EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTemps(Temp temp)
        {
            base.AddObject("Temps", temp);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNLPModel", Name="Item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Item object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static Item CreateItem(global::System.Int32 id, global::System.Int32 value)
        {
            Item item = new Item();
            item.ID = id;
            item.Value = value;
            return item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Int32 _Value;
        partial void OnValueChanging(global::System.Int32 value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PatternID
        {
            get
            {
                return _PatternID;
            }
            set
            {
                OnPatternIDChanging(value);
                ReportPropertyChanging("PatternID");
                _PatternID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatternID");
                OnPatternIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PatternID;
        partial void OnPatternIDChanging(Nullable<global::System.Int32> value);
        partial void OnPatternIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_Items_OutcomePattern", "OutcomePattern")]
        public OutcomePattern OutcomePattern
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OutcomePattern>("DBNLPModel.FK_Items_OutcomePattern", "OutcomePattern").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OutcomePattern>("DBNLPModel.FK_Items_OutcomePattern", "OutcomePattern").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<OutcomePattern> OutcomePatternReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<OutcomePattern>("DBNLPModel.FK_Items_OutcomePattern", "OutcomePattern");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<OutcomePattern>("DBNLPModel.FK_Items_OutcomePattern", "OutcomePattern", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNLPModel", Name="Module")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Module : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Module object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="correctionConstant">Initial value of the CorrectionConstant property.</param>
        /// <param name="parameterCount">Initial value of the ParameterCount property.</param>
        public static Module CreateModule(global::System.Int32 id, global::System.String name, global::System.Int32 correctionConstant, global::System.Int32 parameterCount)
        {
            Module module = new Module();
            module.ID = id;
            module.Name = name;
            module.CorrectionConstant = correctionConstant;
            module.ParameterCount = parameterCount;
            return module;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CorrectionConstant
        {
            get
            {
                return _CorrectionConstant;
            }
            set
            {
                OnCorrectionConstantChanging(value);
                ReportPropertyChanging("CorrectionConstant");
                _CorrectionConstant = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CorrectionConstant");
                OnCorrectionConstantChanged();
            }
        }
        private global::System.Int32 _CorrectionConstant;
        partial void OnCorrectionConstantChanging(global::System.Int32 value);
        partial void OnCorrectionConstantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CorrectionParameter
        {
            get
            {
                return _CorrectionParameter;
            }
            set
            {
                OnCorrectionParameterChanging(value);
                ReportPropertyChanging("CorrectionParameter");
                _CorrectionParameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CorrectionParameter");
                OnCorrectionParameterChanged();
            }
        }
        private Nullable<global::System.Decimal> _CorrectionParameter;
        partial void OnCorrectionParameterChanging(Nullable<global::System.Decimal> value);
        partial void OnCorrectionParameterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ParameterCount
        {
            get
            {
                return _ParameterCount;
            }
            set
            {
                OnParameterCountChanging(value);
                ReportPropertyChanging("ParameterCount");
                _ParameterCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParameterCount");
                OnParameterCountChanged();
            }
        }
        private global::System.Int32 _ParameterCount;
        partial void OnParameterCountChanging(global::System.Int32 value);
        partial void OnParameterCountChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_OutcomeLabel_Module", "OutcomeLabel")]
        public EntityCollection<OutcomeLabel> OutcomeLabels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OutcomeLabel>("DBNLPModel.FK_OutcomeLabel_Module", "OutcomeLabel");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OutcomeLabel>("DBNLPModel.FK_OutcomeLabel_Module", "OutcomeLabel", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_OutcomePattern_Module", "OutcomePattern")]
        public EntityCollection<OutcomePattern> OutcomePatterns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<OutcomePattern>("DBNLPModel.FK_OutcomePattern_Module", "OutcomePattern");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<OutcomePattern>("DBNLPModel.FK_OutcomePattern_Module", "OutcomePattern", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_Predicate_Module", "Predicate")]
        public EntityCollection<Predicate> Predicates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Predicate>("DBNLPModel.FK_Predicate_Module", "Predicate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Predicate>("DBNLPModel.FK_Predicate_Module", "Predicate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNLPModel", Name="OutcomeLabel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OutcomeLabel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OutcomeLabel object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static OutcomeLabel CreateOutcomeLabel(global::System.Int32 id)
        {
            OutcomeLabel outcomeLabel = new OutcomeLabel();
            outcomeLabel.ID = id;
            return outcomeLabel;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                OnModuleIDChanging(value);
                ReportPropertyChanging("ModuleID");
                _ModuleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleID");
                OnModuleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModuleID;
        partial void OnModuleIDChanging(Nullable<global::System.Int32> value);
        partial void OnModuleIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_OutcomeLabel_Module", "Module")]
        public Module Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_OutcomeLabel_Module", "Module").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_OutcomeLabel_Module", "Module").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Module> ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_OutcomeLabel_Module", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Module>("DBNLPModel.FK_OutcomeLabel_Module", "Module", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNLPModel", Name="OutcomePattern")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class OutcomePattern : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new OutcomePattern object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static OutcomePattern CreateOutcomePattern(global::System.Int32 id)
        {
            OutcomePattern outcomePattern = new OutcomePattern();
            outcomePattern.ID = id;
            return outcomePattern;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                OnModuleIDChanging(value);
                ReportPropertyChanging("ModuleID");
                _ModuleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleID");
                OnModuleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _ModuleID;
        partial void OnModuleIDChanging(Nullable<global::System.Int32> value);
        partial void OnModuleIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_Items_OutcomePattern", "Items")]
        public EntityCollection<Item> Items
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Item>("DBNLPModel.FK_Items_OutcomePattern", "Items");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Item>("DBNLPModel.FK_Items_OutcomePattern", "Items", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_OutcomePattern_Module", "Module")]
        public Module Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_OutcomePattern_Module", "Module").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_OutcomePattern_Module", "Module").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Module> ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_OutcomePattern_Module", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Module>("DBNLPModel.FK_OutcomePattern_Module", "Module", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNLPModel", Name="Parameter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Parameter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Parameter object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static Parameter CreateParameter(global::System.Int32 id, global::System.Decimal value)
        {
            Parameter parameter = new Parameter();
            parameter.ID = id;
            parameter.Value = value;
            return parameter;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Decimal _Value;
        partial void OnValueChanging(global::System.Decimal value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PredicateID
        {
            get
            {
                return _PredicateID;
            }
            set
            {
                OnPredicateIDChanging(value);
                ReportPropertyChanging("PredicateID");
                _PredicateID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PredicateID");
                OnPredicateIDChanged();
            }
        }
        private Nullable<global::System.Int32> _PredicateID;
        partial void OnPredicateIDChanging(Nullable<global::System.Int32> value);
        partial void OnPredicateIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_Parameter_Predicate", "Predicate")]
        public Predicate Predicate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predicate>("DBNLPModel.FK_Parameter_Predicate", "Predicate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predicate>("DBNLPModel.FK_Parameter_Predicate", "Predicate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Predicate> PredicateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predicate>("DBNLPModel.FK_Parameter_Predicate", "Predicate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Predicate>("DBNLPModel.FK_Parameter_Predicate", "Predicate", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNLPModel", Name="Predicate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Predicate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Predicate object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="outcomePattern">Initial value of the OutcomePattern property.</param>
        /// <param name="moduleID">Initial value of the ModuleID property.</param>
        public static Predicate CreatePredicate(global::System.Int32 id, global::System.String name, global::System.Int32 outcomePattern, global::System.Int32 moduleID)
        {
            Predicate predicate = new Predicate();
            predicate.ID = id;
            predicate.Name = name;
            predicate.OutcomePattern = outcomePattern;
            predicate.ModuleID = moduleID;
            return predicate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OutcomePattern
        {
            get
            {
                return _OutcomePattern;
            }
            set
            {
                OnOutcomePatternChanging(value);
                ReportPropertyChanging("OutcomePattern");
                _OutcomePattern = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OutcomePattern");
                OnOutcomePatternChanged();
            }
        }
        private global::System.Int32 _OutcomePattern;
        partial void OnOutcomePatternChanging(global::System.Int32 value);
        partial void OnOutcomePatternChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                OnModuleIDChanging(value);
                ReportPropertyChanging("ModuleID");
                _ModuleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ModuleID");
                OnModuleIDChanged();
            }
        }
        private global::System.Int32 _ModuleID;
        partial void OnModuleIDChanging(global::System.Int32 value);
        partial void OnModuleIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_Predicate_Module", "Module")]
        public Module Module
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_Predicate_Module", "Module").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_Predicate_Module", "Module").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Module> ModuleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Module>("DBNLPModel.FK_Predicate_Module", "Module");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Module>("DBNLPModel.FK_Predicate_Module", "Module", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBNLPModel", "FK_Parameter_Predicate", "Parameter")]
        public EntityCollection<Parameter> Parameters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Parameter>("DBNLPModel.FK_Parameter_Predicate", "Parameter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Parameter>("DBNLPModel.FK_Parameter_Predicate", "Parameter", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBNLPModel", Name="Temp")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Temp : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Temp object.
        /// </summary>
        /// <param name="moduleID">Initial value of the ModuleID property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static Temp CreateTemp(global::System.Int32 moduleID, global::System.String value)
        {
            Temp temp = new Temp();
            temp.ModuleID = moduleID;
            temp.Value = value;
            return temp;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModuleID
        {
            get
            {
                return _ModuleID;
            }
            set
            {
                if (_ModuleID != value)
                {
                    OnModuleIDChanging(value);
                    ReportPropertyChanging("ModuleID");
                    _ModuleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModuleID");
                    OnModuleIDChanged();
                }
            }
        }
        private global::System.Int32 _ModuleID;
        partial void OnModuleIDChanging(global::System.Int32 value);
        partial void OnModuleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                if (_Value != value)
                {
                    OnValueChanging(value);
                    ReportPropertyChanging("Value");
                    _Value = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Value");
                    OnValueChanged();
                }
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
    }

    #endregion
    
}
