//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Temp_DBNLPModel", "FK_PredicateParameter_Outcome", "Outcome", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DbWriter.Outcome), "PredicateParameter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbWriter.PredicateParameter), true)]
[assembly: EdmRelationshipAttribute("Temp_DBNLPModel", "FK_PredicateParameter_Predicate", "Predicate", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DbWriter.Predicate), "PredicateParameter", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DbWriter.PredicateParameter), true)]

#endregion

namespace DbWriter
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Temp_DBNLPEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Temp_DBNLPEntities object using the connection string found in the 'Temp_DBNLPEntities' section of the application configuration file.
        /// </summary>
        public Temp_DBNLPEntities() : base("name=Temp_DBNLPEntities", "Temp_DBNLPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Temp_DBNLPEntities object.
        /// </summary>
        public Temp_DBNLPEntities(string connectionString) : base(connectionString, "Temp_DBNLPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Temp_DBNLPEntities object.
        /// </summary>
        public Temp_DBNLPEntities(EntityConnection connection) : base(connection, "Temp_DBNLPEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Model> Models
        {
            get
            {
                if ((_Models == null))
                {
                    _Models = base.CreateObjectSet<Model>("Models");
                }
                return _Models;
            }
        }
        private ObjectSet<Model> _Models;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Outcome> Outcomes
        {
            get
            {
                if ((_Outcomes == null))
                {
                    _Outcomes = base.CreateObjectSet<Outcome>("Outcomes");
                }
                return _Outcomes;
            }
        }
        private ObjectSet<Outcome> _Outcomes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Predicate> Predicates
        {
            get
            {
                if ((_Predicates == null))
                {
                    _Predicates = base.CreateObjectSet<Predicate>("Predicates");
                }
                return _Predicates;
            }
        }
        private ObjectSet<Predicate> _Predicates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PredicateParameter> PredicateParameters
        {
            get
            {
                if ((_PredicateParameters == null))
                {
                    _PredicateParameters = base.CreateObjectSet<PredicateParameter>("PredicateParameters");
                }
                return _PredicateParameters;
            }
        }
        private ObjectSet<PredicateParameter> _PredicateParameters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Models EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModels(Model model)
        {
            base.AddObject("Models", model);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Outcomes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOutcomes(Outcome outcome)
        {
            base.AddObject("Outcomes", outcome);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Predicates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredicates(Predicate predicate)
        {
            base.AddObject("Predicates", predicate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PredicateParameters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPredicateParameters(PredicateParameter predicateParameter)
        {
            base.AddObject("PredicateParameters", predicateParameter);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Temp_DBNLPModel", Name="Model")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Model : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Model object.
        /// </summary>
        /// <param name="modelID">Initial value of the ModelID property.</param>
        /// <param name="correctionConstant">Initial value of the CorrectionConstant property.</param>
        /// <param name="correctionParameter">Initial value of the CorrectionParameter property.</param>
        public static Model CreateModel(global::System.Int32 modelID, global::System.Int32 correctionConstant, global::System.Double correctionParameter)
        {
            Model model = new Model();
            model.ModelID = modelID;
            model.CorrectionConstant = correctionConstant;
            model.CorrectionParameter = correctionParameter;
            return model;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelID
        {
            get
            {
                return _ModelID;
            }
            set
            {
                if (_ModelID != value)
                {
                    OnModelIDChanging(value);
                    ReportPropertyChanging("ModelID");
                    _ModelID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ModelID");
                    OnModelIDChanged();
                }
            }
        }
        private global::System.Int32 _ModelID;
        partial void OnModelIDChanging(global::System.Int32 value);
        partial void OnModelIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CorrectionConstant
        {
            get
            {
                return _CorrectionConstant;
            }
            set
            {
                OnCorrectionConstantChanging(value);
                ReportPropertyChanging("CorrectionConstant");
                _CorrectionConstant = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CorrectionConstant");
                OnCorrectionConstantChanged();
            }
        }
        private global::System.Int32 _CorrectionConstant;
        partial void OnCorrectionConstantChanging(global::System.Int32 value);
        partial void OnCorrectionConstantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CorrectionParameter
        {
            get
            {
                return _CorrectionParameter;
            }
            set
            {
                OnCorrectionParameterChanging(value);
                ReportPropertyChanging("CorrectionParameter");
                _CorrectionParameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CorrectionParameter");
                OnCorrectionParameterChanged();
            }
        }
        private global::System.Double _CorrectionParameter;
        partial void OnCorrectionParameterChanging(global::System.Double value);
        partial void OnCorrectionParameterChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Temp_DBNLPModel", Name="Outcome")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Outcome : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Outcome object.
        /// </summary>
        /// <param name="outcomeID">Initial value of the OutcomeID property.</param>
        /// <param name="outcomeLabel">Initial value of the OutcomeLabel property.</param>
        public static Outcome CreateOutcome(global::System.Int32 outcomeID, global::System.String outcomeLabel)
        {
            Outcome outcome = new Outcome();
            outcome.OutcomeID = outcomeID;
            outcome.OutcomeLabel = outcomeLabel;
            return outcome;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OutcomeID
        {
            get
            {
                return _OutcomeID;
            }
            set
            {
                if (_OutcomeID != value)
                {
                    OnOutcomeIDChanging(value);
                    ReportPropertyChanging("OutcomeID");
                    _OutcomeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OutcomeID");
                    OnOutcomeIDChanged();
                }
            }
        }
        private global::System.Int32 _OutcomeID;
        partial void OnOutcomeIDChanging(global::System.Int32 value);
        partial void OnOutcomeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OutcomeLabel
        {
            get
            {
                return _OutcomeLabel;
            }
            set
            {
                OnOutcomeLabelChanging(value);
                ReportPropertyChanging("OutcomeLabel");
                _OutcomeLabel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OutcomeLabel");
                OnOutcomeLabelChanged();
            }
        }
        private global::System.String _OutcomeLabel;
        partial void OnOutcomeLabelChanging(global::System.String value);
        partial void OnOutcomeLabelChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Temp_DBNLPModel", "FK_PredicateParameter_Outcome", "PredicateParameter")]
        public EntityCollection<PredicateParameter> PredicateParameters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PredicateParameter>("Temp_DBNLPModel.FK_PredicateParameter_Outcome", "PredicateParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PredicateParameter>("Temp_DBNLPModel.FK_PredicateParameter_Outcome", "PredicateParameter", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Temp_DBNLPModel", Name="Predicate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Predicate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Predicate object.
        /// </summary>
        /// <param name="predicateID">Initial value of the PredicateID property.</param>
        /// <param name="predicateLabel">Initial value of the PredicateLabel property.</param>
        public static Predicate CreatePredicate(global::System.Int32 predicateID, global::System.String predicateLabel)
        {
            Predicate predicate = new Predicate();
            predicate.PredicateID = predicateID;
            predicate.PredicateLabel = predicateLabel;
            return predicate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PredicateID
        {
            get
            {
                return _PredicateID;
            }
            set
            {
                if (_PredicateID != value)
                {
                    OnPredicateIDChanging(value);
                    ReportPropertyChanging("PredicateID");
                    _PredicateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PredicateID");
                    OnPredicateIDChanged();
                }
            }
        }
        private global::System.Int32 _PredicateID;
        partial void OnPredicateIDChanging(global::System.Int32 value);
        partial void OnPredicateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PredicateLabel
        {
            get
            {
                return _PredicateLabel;
            }
            set
            {
                OnPredicateLabelChanging(value);
                ReportPropertyChanging("PredicateLabel");
                _PredicateLabel = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PredicateLabel");
                OnPredicateLabelChanged();
            }
        }
        private global::System.String _PredicateLabel;
        partial void OnPredicateLabelChanging(global::System.String value);
        partial void OnPredicateLabelChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Temp_DBNLPModel", "FK_PredicateParameter_Predicate", "PredicateParameter")]
        public EntityCollection<PredicateParameter> PredicateParameters
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<PredicateParameter>("Temp_DBNLPModel.FK_PredicateParameter_Predicate", "PredicateParameter");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<PredicateParameter>("Temp_DBNLPModel.FK_PredicateParameter_Predicate", "PredicateParameter", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Temp_DBNLPModel", Name="PredicateParameter")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PredicateParameter : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PredicateParameter object.
        /// </summary>
        /// <param name="predicateID">Initial value of the PredicateID property.</param>
        /// <param name="outcomeID">Initial value of the OutcomeID property.</param>
        /// <param name="parameter">Initial value of the Parameter property.</param>
        public static PredicateParameter CreatePredicateParameter(global::System.Int32 predicateID, global::System.Int32 outcomeID, global::System.Double parameter)
        {
            PredicateParameter predicateParameter = new PredicateParameter();
            predicateParameter.PredicateID = predicateID;
            predicateParameter.OutcomeID = outcomeID;
            predicateParameter.Parameter = parameter;
            return predicateParameter;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PredicateID
        {
            get
            {
                return _PredicateID;
            }
            set
            {
                if (_PredicateID != value)
                {
                    OnPredicateIDChanging(value);
                    ReportPropertyChanging("PredicateID");
                    _PredicateID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PredicateID");
                    OnPredicateIDChanged();
                }
            }
        }
        private global::System.Int32 _PredicateID;
        partial void OnPredicateIDChanging(global::System.Int32 value);
        partial void OnPredicateIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OutcomeID
        {
            get
            {
                return _OutcomeID;
            }
            set
            {
                if (_OutcomeID != value)
                {
                    OnOutcomeIDChanging(value);
                    ReportPropertyChanging("OutcomeID");
                    _OutcomeID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("OutcomeID");
                    OnOutcomeIDChanged();
                }
            }
        }
        private global::System.Int32 _OutcomeID;
        partial void OnOutcomeIDChanging(global::System.Int32 value);
        partial void OnOutcomeIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Parameter
        {
            get
            {
                return _Parameter;
            }
            set
            {
                OnParameterChanging(value);
                ReportPropertyChanging("Parameter");
                _Parameter = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Parameter");
                OnParameterChanged();
            }
        }
        private global::System.Double _Parameter;
        partial void OnParameterChanging(global::System.Double value);
        partial void OnParameterChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Temp_DBNLPModel", "FK_PredicateParameter_Outcome", "Outcome")]
        public Outcome Outcome
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Outcome>("Temp_DBNLPModel.FK_PredicateParameter_Outcome", "Outcome").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Outcome>("Temp_DBNLPModel.FK_PredicateParameter_Outcome", "Outcome").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Outcome> OutcomeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Outcome>("Temp_DBNLPModel.FK_PredicateParameter_Outcome", "Outcome");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Outcome>("Temp_DBNLPModel.FK_PredicateParameter_Outcome", "Outcome", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Temp_DBNLPModel", "FK_PredicateParameter_Predicate", "Predicate")]
        public Predicate Predicate
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predicate>("Temp_DBNLPModel.FK_PredicateParameter_Predicate", "Predicate").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predicate>("Temp_DBNLPModel.FK_PredicateParameter_Predicate", "Predicate").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Predicate> PredicateReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Predicate>("Temp_DBNLPModel.FK_PredicateParameter_Predicate", "Predicate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Predicate>("Temp_DBNLPModel.FK_PredicateParameter_Predicate", "Predicate", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
